# We have 2 stage Test and Deploy
stages:
  # - test
  - deploy

# Config cache
cache:
  paths:
    - node_modules/

# # Test job
# test:
#   # Docker image
#   image: node:latest
#   # Attach Test job to Test stage
#   stage: test
#   # Config to use GitLab Shared Runner with Executor Docker
#   tags:
#     - docker
#   script:
#     - npm install
#   # Defines the names of branches and tags the job runs for
#   only:
#     - develop

# Deploy job
deploy:
  type: deploy
  # Attach Deploy job to Deploy stage
  stage: deploy
  # Config to use our Runner with Executor Shell
  tags:
    - my-shell-runner
  before_script:
    - echo "PATH='${PATH}'"
    - export PATH="$PATH:/home/ec2-user/.nvm/versions/node/v16.0.0/bin"
  script:
    - echo "PATH='${PATH}'"
    - who
    # - sudo chmod +x /home/ec2-user/project-ci
    # Only copy changed files to project folder
    - cp -r -u * /var/www/project-ci
    - cd /var/www/project-ci
    - npm -v
    - node -v
    - npm install
    # Restart NodeJS service
    - forever stop index.js || true
    - forever start index.js
  only:
    - develop